name: crystal_ball
description: A game made with Flame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  binarize: ^1.5.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flame: 1.18.0
  flame_bloc: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_shaders: ^0.1.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  mockingjay: ^0.5.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/licenses/macondo/
    - google_fonts/
  shaders:
    - shaders/platforms.frag
    - shaders/the_ball.frag
    - shaders/mesh_25_gradient.frag
    - shaders/ground.frag
    - shaders/rocks.frag
    - shaders/fog.frag
